config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace 'api' do 
    resources :messages
    resources :conversations
    resources :users   
  end  

  devise_for :users

  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/conversations_controller.rb
module Api
    class ConversationsController < ApplicationController
        def index
            conversations = Conversation.find_by_sql("SELECT * FROM conversations 
            WHERE sender_id ='#{current_user.id}'")
            render json: {status: 'SUCCESS', data: conversations}, status: :ok
        end

        def show
            messages = Message.find_by_sql("SELECT * FROM messages 
            WHERE user_id ='#{current_user.id}'AND conversation_id = '#{params[:id]}' ")
            render json: {status: 'SUCCESS', data: messages}, status: :ok
        end
    end
end

app/controllers/api/messages_controller.rb
module Api
    class MessagesController < ApplicationController
        def index
            messages = Message.find_by_sql("SELECT * FROM messages 
            WHERE user_id ='#{current_user.id}' ")
            render json: {status: 'SUCCESS', data: messages}, status: :ok
        end

        def show
            message = Message.find_by_sql("SELECT * FROM messages 
            WHERE user_id ='#{current_user.id}' AND id = '#{params[:id]}'")
            render json: {status: 'SUCCESS', data: message}, status: :ok
        end
    end
end

app/controllers/api/users_controller.rb
module Api
    class UsersController < ApplicationController
        def index
            users = User.order('created_at DESC');
            render json: {status: 'SUCCESS', data: users}, status: :ok
        end

        def show
            user = User.find(params[:id])
            render json: {status: 'SUCCESS', data: user}, status: :ok
        end

        def create
            user = User.new(user_param)
            if user.save
                render json: {status: 'SUCCESS', message: 'Saved User', data: user}, status: :ok
            else
                render json: {status: 'ERROR', message: 'User not saved',
                data: user.errors}, status: :unprocessable_entity
            end
        end

        def user_param
            params.permit(:username, :email, :password)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  is_cancan=true
  begin
    Kernel.const_get('CanCan')
  rescue
    is_cancan=false
  end

  if is_cancan
    rescue_from CanCan::AccessDenied do |exception|
      flash[:error] = 'Access denied.'
      redirect_to root_url
    end
  end

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
 end
  #protect_from_forgery with: :exception
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])

    add_to_conversations unless conversated?

    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])

    session[:conversations].delete(@conversation.id)

    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])

    #Update Chat_counts in User Table
    conversationsSentCount = Conversation.where(:sender_id => current_user.id).count
    conversationsRecievedCount = Conversation.where(:recipient_id => current_user.id).count
    allConversationsCount = conversationsSentCount+conversationsRecievedCount
    User.find_by_sql("UPDATE users
                      SET chats_count = '#{allConversationsCount}'
                      WHERE id ='#{current_user.id}';")
    #update messages_count in Conversation Table
    Conversation.all.each do |conversation|
      messagesCount = Message.where(:conversation_id => conversation.id).count
      Conversation.find_by_sql("UPDATE conversations
                      SET messages_count = '#{messagesCount}'
                      WHERE sender_id ='#{current_user.id}';")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/conversations/_conversation.html.erb
<li>
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-heading">
      <%= link_to conversation.opposed_user(user).username, '', class: 'toggle-window' %>
      <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
    </div>

    <div class="panel-body" style="display: none;">
      <div class="messages-list">
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>
      <form class="new_message">
        <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
        <input name="user_id" type="hidden" value="<%= user.id %>">
        <textarea name="body" class="form-control"></textarea>
        <input type="submit" class="btn btn-success" value="Send">
      </form>
    </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/home/index.html.erb
<div class="row">

  <nav class="navbar navbar-light" style="background-color: #337ab7;">
    <a class="navbar-brand" style="color: white;">InstaBug Chat Application</a>
    <div class="dropdown" style="text-align: right;padding-top: 15px;font-size: large;padding-right: 5px;">
      <a class="nav-link dropdown-toggle"  id="navbarDropdown" role="button" data-toggle="dropdown" style="color: white;">
        <%= current_user.username%>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" >
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </div>
  </nav>

  <div class="col-md-9">
    <ul id="conversations-list">
      <% @conversations.each do |conversation| %>
        <%= render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.username, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaBug Chat Application</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<li>
  <div class="row">
    <div class="<%= user.id == message.user_id ? 'message-sent' : 'message-received' %>">
      <%= message.body %>
    </div>
  </div>
</li>